# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_auto_20180701_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wordadmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'admin_password',
            },
        ),
    ]
